plugins {
    id 'com.android.application'
}

android {
    compileSdk = 36

    defaultConfig {
        applicationId = "edu.cs4730.androidbeaconlibrary"
        minSdk = 31
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace = 'edu.cs4730.androidbeaconlibrary'
    buildFeatures {
        viewBinding = true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    //https://mvnrepository.com/artifact/org.altbeacon/android-beacon-library  to find newer version.
    implementation 'org.altbeacon:android-beacon-library:2.21.1'


}